/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jenkin_uestc_BsDiff */

#ifndef _Included_com_jenkin_uestc_BsDiff
#define _Included_com_jenkin_uestc_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jenkin_uestc_BsDiff
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jenkin_uestc_BsDiff_genDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
